sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kent/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kent/react-test npm test

after_success:
  - docker build -t kent/multi-client ./client 
  - docker build -t kent/multi-nginx ./nginx 
  - docker build -t kent/multi-server ./server 
  - docker build -t kent/multi-worker ./worker 
  # Log in to the docker CLI
  - docker login --username "$DOCKER_ID" --password "$DOCKER_PASSWORD"
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker tag kent/multi-client:latest kent831213/dockerhub:kent/multi-client
  - docker tag kent/multi-nginx:latest kent831213/dockerhub:kent/multi-nginx
  - docker tag kent/multi-server:latest kent831213/dockerhub:kent/multi-server
  - docker tag kent/multi-worker:latest kent831213/dockerhub:kent/multi-worker


  - docker push kent831213/dockerhub:kent/multi-client
  - docker push kent831213/dockerhub:kent/multi-nginx
  - docker push kent831213/dockerhub:kent/multi-server
  - docker push kent831213/dockerhub:kent/multi-worker