sudo: required
services:
  - docker

before_install:
  - docker build -t kent/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kent/react-test npm test 

after_success:
  - docker build -t kent/multi-client ./client
  - docker build -t kent/multi-nginx ./nginx
  - docker build -t kent/multi-server ./server
  - docker build -t kent/multi-worker ./worker
  # Log in to the docker CLI
  - echo "\$DOCKER_PASSWORD" | docker login -u "\$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kent/multi-client
  - docker push kent/multi-nginx
  - docker push kent/multi-server
  - docker push kent/multi-worker
